# Generated by Django 2.2.13 on 2021-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0082_challengephasesplit_show_execution_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('challenge_id', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=200)),
                ('a_1', models.CharField(blank=True, max_length=500)),
                ('a_2', models.CharField(blank=True, max_length=500)),
                ('a_3', models.CharField(blank=True, max_length=500)),
                ('a_4', models.CharField(blank=True, max_length=500)),
                ('a_5', models.CharField(blank=True, max_length=500)),
                ('a_6', models.CharField(blank=True, max_length=500)),
                ('a_7', models.CharField(blank=True, max_length=500)),
                ('a_8', models.CharField(blank=True, max_length=500)),
                ('a_9', models.CharField(blank=True, max_length=500)),
                ('a_10', models.CharField(blank=True, max_length=500)),
                ('a_11', models.CharField(blank=True, max_length=500)),
                ('a_12', models.CharField(blank=True, max_length=500)),
                ('a_13', models.CharField(blank=True, max_length=500)),
                ('a_14', models.CharField(blank=True, max_length=500)),
                ('a_15', models.CharField(blank=True, max_length=500)),
                ('a_16', models.CharField(blank=True, max_length=500)),
                ('a_17', models.CharField(blank=True, max_length=500)),
                ('a_18', models.CharField(blank=True, max_length=500)),
                ('a_19', models.CharField(blank=True, max_length=500)),
                ('a_20', models.CharField(blank=True, max_length=500)),
                ('a_21', models.CharField(blank=True, max_length=500)),
                ('a_22', models.CharField(blank=True, max_length=500)),
                ('a_23', models.CharField(blank=True, max_length=500)),
                ('a_24', models.CharField(blank=True, max_length=500)),
                ('a_25', models.CharField(blank=True, max_length=500)),
                ('a_26', models.CharField(blank=True, max_length=500)),
                ('a_27', models.CharField(blank=True, max_length=500)),
                ('a_28', models.CharField(blank=True, max_length=500)),
                ('a_29', models.CharField(blank=True, max_length=500)),
                ('a_30', models.CharField(blank=True, max_length=500)),
                ('a_31', models.CharField(blank=True, max_length=500)),
                ('a_32', models.CharField(blank=True, max_length=500)),
                ('a_33', models.CharField(blank=True, max_length=500)),
                ('a_34', models.CharField(blank=True, max_length=500)),
                ('a_35', models.CharField(blank=True, max_length=500)),
                ('a_36', models.CharField(blank=True, max_length=500)),
                ('a_37', models.CharField(blank=True, max_length=500)),
                ('a_38', models.CharField(blank=True, max_length=500)),
                ('a_39', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'questionnaire_data',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_static_dataset_code_upload',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Static Dataset Code Upload Based'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='submission_time_limit',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='challengephase',
            name='annotations_uploaded_using_cli',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='aws_region',
            field=models.CharField(blank=True, default='us-east-1', max_length=50, null=True),
        ),
    ]
